Sanitize AddSnackScreen user input
DouglasHalse/snackAttackTrack pull request #77
Opened 2024-12-23 18:39 UTC by philiptekin

Added sanitizing of user input when adding snacks

2024-12-23 18:40 UTC, philiptekin commented
Don't know where to put error messages when input is wrong, where would the best place for that be?

2024-12-23 18:53 UTC, DouglasHalse approved these changes

2024-12-23 18:54 UTC, DouglasHalse commented
I reckon we could create a generic Popup with the error message and show that if the input is wrong

2025-01-11 09:32 UTC, DouglasHalse commented
I have updated ErrorMessagePopup, we could use trigger that one when the snack name is empty

2025-01-20 05:43 UTC, DouglasHalse requested changes

2025-01-28 17:55 UTC, closed without merging